<a href="https://colab.research.google.com/github/Yesimg/Fake-Real-News_NLP/blob/main/retail_sales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [12]:
import pandas as pd

# The 'FileNotFoundError' indicates that the file 'customer_shopping_behavior.csv' was not found.
# Since Google Drive is mounted, the file is likely in your Drive.
# Update the path below to the correct location of your CSV file in Google Drive.
# For example, if it's directly in 'My Drive', the path would be '/content/drive/MyDrive/customer_shopping_behavior.csv'.
# If it's in a subfolder, e.g., 'data', it would be '/content/drive/MyDrive/data/customer_shopping_behavior.csv'.
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Business_Case_Retail-Sales/customer_shopping_behavior.csv')

df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

describe "all" to get the summarize of both, numerical and categorical values

In [14]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

Let's check if there is any "null" values

In [15]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

Column 'Review Rating' has nulls. To replace them I'm going to use the the median within each category. It is important to notice that I am not usong the overall median value because this is affected by outliers whereas the category one do not have this bias.

In [16]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [17]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

I will modify all column's names into lowercase separeted by underscores

In [18]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [19]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [20]:
#create a column 'age_group'

In [21]:
labels = ['Young Adult', 'Adult', 'Middle-Aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels= labels)

In [22]:
df[['age','age_group']].head()

   age    age_group
0   55  Middle-Aged
1   19  Young Adult
2   50  Middle-Aged
3   21  Young Adult
4   45  Middle-Aged

In [23]:
df['frequency_of_purchases'].head()

0    Fortnightly
1    Fortnightly
2         Weekly
3         Weekly
4       Annually
Name: frequency_of_purchases, dtype: object

In [24]:
# create column purchase_frequency_days

#first create a dictionary that maps each frequency in number of days in the column
frequency_mapping = {
'Fortnightly':14,
'Weekly':7,
'Monthly':30,
'Quarterly':90,
'Bi-Weekly':14,
'Annually':365,
'Every 3 Months':90

}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [25]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [26]:
# i am going to check if the columns  'discount_applied' and 'promo_code_used' are equals and i have redundancy.
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [27]:
df = df.drop(columns=['promo_code_used'], axis=1)

In [28]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 58.1 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12

In [ ]:
pip install --upgrade pip

CREATE AN SQL DATABASE

In [ ]:
pip install --upgrade SQLAlchemy

In [31]:
#import sqlalchemy
#print(sqlalchemy.__version__)

In [ ]:
%pip install "SQLAlchemy<2.0"
%pip install pymysql

In [ ]:
from sqlalchemy import create_engine


#Mysql connection
username = 'root'
password = '7899'
host = '127.0.0.1'
port= 3306
database = 'customer_behavior'


engine = create_engine(f'mysql+pymysql://{username}:{password}@{host}:{port}/{database}')

#Write the DataFrame to MySQL
table_name = "customer"
df.to_sql(table_name, con=engine, if_exists="replace", index=False)

#Read the data back from MySQL to verify
pd.read_sql(f'SELECT * FROM customer LIMIT 5', con=engine)

In [ ]:
import pandas as pd
pd.read_sql(f'SELECT * FROM customer LIMIT 5', con=engine)

In [ ]:
pd.read_sql(
    """
    select subscription_status,
        count(customer_id) AS total_customers,
        round(avg(purchase_amount),2) as avg_spend,
        sum(purchase_amount) as total_revenue
    from customer
    group by subscription_status
    order by total_revenue desc
    """,
    con=engine
)

In [ ]:
#Q6. Which 5 products have the highest percentage of purchases with discounts applied?

pd.read_sql(
    """
    select subscription_status,
        count(customer_id) AS total_customers,
        round(avg(purchase_amount),2) as avg_spend,
        sum(purchase_amount) as total_revenue
    from customer
    group by subscription_status
    order by total_revenue desc
    """,
    con=engine
)

# **AI Product: Customer Growth Copilot**

User
* Marketing Manager
* CRM Manager
* E-commerce Manager

**Business Problem**

A retailer has 20,000 customers.
Marketing budget is limited.

Who should receive:

- discounts?
- loyalty offers?
- premium memberships?
- reactivation campaigns?

Let's solve the "guessing problem" of most companies

**KPI 1: Customer Health Score**

Based on:

* Previous purchases
* Subscription status
* Average spend
* Discount usage
* Review rating

In [34]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [47]:
#Create a sub dataset called 'customer_id' and then calculates the total number of purchases (count), the average purchase amount (mean),
#and the average review_rating for each unique customer.
#This helps to consolidate customer-level information
customer_df = df.groupby('customer_id').agg({
          'age': 'first',
          'gender': 'first',
          'purchase_amount': ['sum', 'mean'],
          'review_rating': 'mean',
          'previous_purchases': 'max',
          'subscription_status': 'first',
          'discount_applied': lambda x: (x == 'Yes').mean() * 100
      })

In [48]:
# First, ensure that 'customer_df = df.groupby(...).agg(...)' is run in cell YRpOGxHzq4e6.
# Then, flatten the MultiIndex columns before renaming.
customer_df.columns = ['_'.join(col).strip() if isinstance(col, tuple) else col for col in customer_df.columns.values]

customer_df.columns = [
    'age',
    'gender',
    'total_spend',
    'avg_spend',
    'avg_rating',
    'previous_purchases',
    'subscription_status',
    'discount_usage_pct'
]

customer_df = customer_df.reset_index()

customer_df.head()

,customer_id,age,gender,total_spend,avg_spend,avg_rating,previous_purchases,subscription_status,discount_usage_pct
0,1,55,Male,53,53.0,3.1,14,Yes,100.0
1,2,19,Male,64,64.0,3.1,2,Yes,100.0
2,3,50,Male,73,73.0,3.1,23,Yes,100.0
3,4,21,Male,90,90.0,3.5,49,Yes,100.0
4,5,45,Male,49,49.0,2.7,31,Yes,100.0